package View;

import java.awt.Component;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.awt.image.PixelGrabber;
import java.io.File;
import java.io.IOException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author mateus
 */
public class InserirImagens1 extends javax.swing.JFrame {

    //Inicia Buffered
    BufferedImage buff1 = null;
    BufferedImage buff2 = null;

    private static final Component componente = new Component() {
    };

    // Função que recebe uma imagem do tipo Buffered e calcula a quantidade de pixels
    private static int[] pegaPixels(BufferedImage imagem) {
        final int width = imagem.getWidth(componente);
        final int height = imagem.getHeight(componente);
        int size = width * height;

        PixelGrabber pixel = new PixelGrabber(imagem, 0, 0, width, height, new int[size], 0, width);
        pixel.startGrabbing();
        return (int[]) pixel.getPixels();
    }

    /**
     * Creates new form InserirImagens
     */
    public InserirImagens1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCalcular = new javax.swing.JButton();
        txtImagem1 = new javax.swing.JTextField();
        txtImagem2 = new javax.swing.JTextField();
        btnBuscar1 = new javax.swing.JButton();
        btnBuscar2 = new javax.swing.JButton();
        lblImagem1 = new javax.swing.JLabel();
        lblImagem2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCalcular.setText("Calcular");
        btnCalcular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCalcularMouseClicked(evt);
            }
        });

        txtImagem1.setEditable(false);
        txtImagem1.setText("Primeira Imagem");
        txtImagem1.setEnabled(false);
        txtImagem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImagem1ActionPerformed(evt);
            }
        });

        txtImagem2.setText("Segunda Imagem");
        txtImagem2.setEnabled(false);

        btnBuscar1.setText("Buscar");
        btnBuscar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscar1MouseClicked(evt);
            }
        });
        btnBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar1ActionPerformed(evt);
            }
        });

        btnBuscar2.setText("Buscar");
        btnBuscar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscar2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImagem2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtImagem2, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblImagem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtImagem1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCalcular)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagem1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtImagem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblImagem2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtImagem2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar2))
                .addGap(60, 60, 60)
                .addComponent(btnCalcular)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtImagem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImagem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImagem1ActionPerformed

    private void btnBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscar1ActionPerformed

    private void btnCalcularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalcularMouseClicked

        calcular();

    }//GEN-LAST:event_btnCalcularMouseClicked

    private void btnBuscar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscar1MouseClicked

        // Abrir um seletor de arquivos
        JFileChooser file = new JFileChooser();
        file.setDialogTitle("Procurar imagem");
        file.setFileSelectionMode(JFileChooser.FILES_ONLY);

        //Filtro para aparecer somente imagens
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Imagem", "jpg", "png", "jpeg");

        file.setFileFilter(filtro);
        int retorno = file.showOpenDialog(this);

        // Recebe caminho da imagem
        File arquivo = file.getSelectedFile();

        String caminho = arquivo.getPath();

        if (retorno == JFileChooser.APPROVE_OPTION) {
            // Insere caminho no JText
            txtImagem1.setText(caminho);

            // Insere imagem na label
            lblImagem1.setIcon(new ImageIcon(new ImageIcon(arquivo.getPath()).getImage().getScaledInstance(284, 135, Image.SCALE_DEFAULT)));
        }
        // Recebe imagem e grava na variavel do tipo File
        File img1 = new File(caminho);

        try {
            // Lê imagem e armazena na variavel Buferred
            buff1 = ImageIO.read(img1);
        } catch (IOException ex) {
            Logger.getLogger("Erro: " + ex);
        }
    }//GEN-LAST:event_btnBuscar1MouseClicked

    private void btnBuscar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscar2MouseClicked

        JFileChooser file = new JFileChooser();
        file.setDialogTitle("Procurar segunda imagem");
        file.setFileSelectionMode(JFileChooser.FILES_ONLY);

        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Imagem", "jpg", "png", "jpeg");

        file.setFileFilter(filtro);
        int retorno = file.showOpenDialog(this);

        File arquivo = file.getSelectedFile();

        String caminho = arquivo.getPath();
        txtImagem2.setText(caminho);

        lblImagem2.setIcon(new ImageIcon(new ImageIcon(arquivo.getPath()).getImage().getScaledInstance(284, 135, Image.SCALE_DEFAULT)));

        File img2 = new File(caminho);

        try {
            buff2 = ImageIO.read(img2);
        } catch (IOException ex) {
            Logger.getLogger("Erro: " + ex);
        }
    }//GEN-LAST:event_btnBuscar2MouseClicked

    public void calcular() {
        int[] pixels1 = pegaPixels(buff1);
        int[] pixels2 = pegaPixels(buff2);

        if (Arrays.equals(pixels1, pixels2)) {
            JOptionPane.showMessageDialog(null, "As imagens são iguais!");
        } else {
            JOptionPane.showMessageDialog(null, "As imagens são diferentes!");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InserirImagens1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InserirImagens1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InserirImagens1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InserirImagens1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InserirImagens1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar1;
    private javax.swing.JButton btnBuscar2;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JLabel lblImagem1;
    private javax.swing.JLabel lblImagem2;
    private javax.swing.JTextField txtImagem1;
    private javax.swing.JTextField txtImagem2;
    // End of variables declaration//GEN-END:variables
}
